trigger:
  batch: "true"
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - "**/*.md"

pr:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - "**/*.md"

parameters:
  - name: publishPackages
    displayName: 'Publish Packages'
    type: boolean
    default: false

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - name: versionSuffix
        value: ""
  - ${{ if and(eq(variables['Build.SourceBranchName'], 'develop'), ne(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
      - name: versionSuffix
        value: "dev.$(build.buildnumber)"
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
      - name: versionSuffix
        value: "pr$(System.PullRequest.PullRequestNumber).$(build.buildnumber)"
  - ${{ if and(ne(variables['Build.SourceBranchName'], 'master'), ne(variables['Build.SourceBranchName'], 'develop'), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/'))) }}:
      - name: versionSuffix
        value: "feature.$(build.buildnumber)"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: "Test"
    inputs:
      command: test
      arguments: '--no-build --collect:"XPlat Code Coverage"'

  - task: DotNetCoreCLI@2
    displayName: "Pack"
    inputs:
      command: pack
      arguments: "-o $(Build.ArtifactStagingDirectory) --no-build"

  - task: PublishCodeCoverageResults@2
    displayName: "Publish Coverage Report"
    inputs:
      summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"
      failIfCoverageEmpty: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Build Artifacts"
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: ArtifactStagingDirectory

  - task: NuGetAuthenticate@1
    displayName: "NuGet Authenticate"
    condition: and(succeeded(), ${{parameters.publishPackages}})

  - task: NuGetCommand@2
    displayName: "NuGet Push"
    condition: and(succeeded(), ${{parameters.publishPackages}})
    inputs:
      command: push
      publishVstsFeed: "CluedIn"
