trigger:
  batch: "true"
  branches:
    include:
      - master
      - develop

pr:
  branches:
    include:
      - master
      - develop

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - name: versionSuffix
        value: "$(build.buildnumber)"
  - ${{ if and(eq(variables['Build.SourceBranchName'], 'develop'), ne(variables['Build.SourceBranch'], 'refs/heads/master')) }}:
      - name: versionSuffix
        value: "dev.$(build.buildnumber)"
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
      - name: versionSuffix
        value: "pr$(System.PullRequest.PullRequestNumber).$(build.buildnumber)"
  - ${{ if and(ne(variables['Build.SourceBranchName'], 'master'), ne(variables['Build.SourceBranchName'], 'develop'), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/'))) }}:
      - name: versionSuffix
        value: "feature.$(build.buildnumber)"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: '--no-build --collect:"XPlat Code Coverage"'

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      arguments: "-o $(Build.ArtifactStagingDirectory) --no-build"

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"
      failIfCoverageEmpty: true
    displayName: "Publish Coverage Report"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: ArtifactStagingDirectory
    displayName: "Publish Build Artifacts"

  - task: NuGetAuthenticate@1
    displayName: "NuGet Authenticate"

  - task: NuGetCommand@2
    displayName: "NuGet Push"
    inputs:
      command: push
      publishVstsFeed: "CluedIn"
